[0m10:43:24.183200 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10769a3c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088e7c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088e7b10>]}


============================== 10:43:24.185808 | 1d1aafe1-9b0e-40c5-9c82-236fddde91dd ==============================
[0m10:43:24.185808 [info ] [MainThread]: Running with dbt=1.9.0
[0m10:43:24.186111 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/diaw/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init dbt_notlimitail_tl', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:43:24.195051 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/dbt/include/starter_project
[0m10:43:24.198463 [info ] [MainThread]: 
Your new dbt project "dbt_notlimitail_tl" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:43:24.198613 [info ] [MainThread]: Setting up your profile.
[0m10:47:33.613471 [info ] [MainThread]: Profile dbt_notlimitail_tl written to /Users/diaw/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m10:47:33.637745 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 249.48885, "process_in_blocks": "0", "process_kernel_time": 0.435841, "process_mem_max_rss": "346505216", "process_out_blocks": "0", "process_user_time": 1.397122}
[0m10:47:33.640469 [debug] [MainThread]: Command `dbt init` succeeded at 10:47:33.640292 after 249.49 seconds
[0m10:47:33.641238 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x116f2fce0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x116f98ef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x116f029c0>]}
[0m10:47:33.642105 [debug] [MainThread]: Flushing usage events
[0m10:47:34.057564 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:57:12.147474 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1097363c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c2efd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c2efb10>]}


============================== 10:57:12.150299 | 38c27812-259c-4911-9c82-9fc243529be2 ==============================
[0m10:57:12.150299 [info ] [MainThread]: Running with dbt=1.9.0
[0m10:57:12.150601 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/diaw/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m10:57:12.150856 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/diaw/Downloads/dbt_notlimitail_tl/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:57:12.153654 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04306779, "process_in_blocks": "0", "process_kernel_time": 0.114554, "process_mem_max_rss": "98942976", "process_out_blocks": "0", "process_user_time": 0.590703}
[0m10:57:12.153879 [debug] [MainThread]: Command `dbt run` failed at 10:57:12.153838 after 0.04 seconds
[0m10:57:12.154034 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c213230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c1eb530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c163790>]}
[0m10:57:12.154170 [debug] [MainThread]: Flushing usage events
[0m10:57:12.570221 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:07:17.706098 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103a763c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104cbfd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104cbfb10>]}


============================== 11:07:17.708854 | c8c542a1-bca5-4434-9796-1c485ad35c59 ==============================
[0m11:07:17.708854 [info ] [MainThread]: Running with dbt=1.9.0
[0m11:07:17.709161 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/diaw/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m11:07:17.709558 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/diaw/Downloads/dbt_notlimitail_tl/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:07:17.711032 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.041226417, "process_in_blocks": "0", "process_kernel_time": 0.105705, "process_mem_max_rss": "100368384", "process_out_blocks": "0", "process_user_time": 0.564877}
[0m11:07:17.711287 [debug] [MainThread]: Command `dbt deps` failed at 11:07:17.711242 after 0.04 seconds
[0m11:07:17.711459 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104be3230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104bbb530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b33680>]}
[0m11:07:17.711610 [debug] [MainThread]: Flushing usage events
[0m11:07:18.103647 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:05:06.709894 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056e63c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106937b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106937c50>]}


============================== 15:05:06.712620 | 7c8e4e24-5bad-4aea-b7d8-bf9aabcd83fe ==============================
[0m15:05:06.712620 [info ] [MainThread]: Running with dbt=1.9.0
[0m15:05:06.712910 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/diaw/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt test', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:05:06.713160 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/diaw/Downloads/dbt_notlimitail_tl/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:05:06.714582 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.03546629, "process_in_blocks": "0", "process_kernel_time": 0.110467, "process_mem_max_rss": "100188160", "process_out_blocks": "0", "process_user_time": 0.559793}
[0m15:05:06.714841 [debug] [MainThread]: Command `dbt test` failed at 15:05:06.714793 after 0.04 seconds
[0m15:05:06.715004 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10685f360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106823650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067bb680>]}
[0m15:05:06.715154 [debug] [MainThread]: Flushing usage events
[0m15:05:07.099488 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:08:52.291223 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1046ee3c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105eefd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105eefb10>]}


============================== 15:08:52.293926 | 44b22c53-5d47-4dbe-b671-1e4660a3e769 ==============================
[0m15:08:52.293926 [info ] [MainThread]: Running with dbt=1.9.0
[0m15:08:52.294262 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/diaw/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt deps', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:08:52.294643 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/diaw/Downloads/dbt_notlimitail_tl/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:08:52.296046 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.03808621, "process_in_blocks": "0", "process_kernel_time": 0.110104, "process_mem_max_rss": "100712448", "process_out_blocks": "0", "process_user_time": 0.548434}
[0m15:08:52.296260 [debug] [MainThread]: Command `dbt deps` failed at 15:08:52.296215 after 0.04 seconds
[0m15:08:52.296419 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105e13230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105deb530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105d63680>]}
[0m15:08:52.296553 [debug] [MainThread]: Flushing usage events
[0m15:08:52.737938 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:07:24.518480 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f523c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10919bb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10919bd90>]}


============================== 10:07:24.521274 | 7cfb1584-0a81-4f93-b8a3-2967833ab049 ==============================
[0m10:07:24.521274 [info ] [MainThread]: Running with dbt=1.9.0
[0m10:07:24.521575 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/diaw/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:07:24.521823 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/diaw/Downloads/dbt_notlimitail_tl/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:07:24.523549 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.042474333, "process_in_blocks": "0", "process_kernel_time": 0.115189, "process_mem_max_rss": "99860480", "process_out_blocks": "0", "process_user_time": 0.558209}
[0m10:07:24.523814 [debug] [MainThread]: Command `dbt run` failed at 10:07:24.523769 after 0.04 seconds
[0m10:07:24.523990 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1090bf230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109097530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10900f790>]}
[0m10:07:24.524143 [debug] [MainThread]: Flushing usage events
[0m10:07:24.946775 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:15:56.788293 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1080ee3c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109337b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109337d90>]}


============================== 10:15:56.791194 | 684073fb-d011-446c-a29b-5b43d9c33631 ==============================
[0m10:15:56.791194 [info ] [MainThread]: Running with dbt=1.9.0
[0m10:15:56.791546 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/diaw/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt docs generate', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:15:56.791835 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/diaw/Downloads/dbt_notlimitail_tl/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:15:56.793523 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.038357418, "process_in_blocks": "0", "process_kernel_time": 0.096579, "process_mem_max_rss": "100433920", "process_out_blocks": "0", "process_user_time": 0.557423}
[0m10:15:56.793784 [debug] [MainThread]: Command `dbt docs generate` failed at 10:15:56.793733 after 0.04 seconds
[0m10:15:56.793951 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10925b490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109233530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1091af790>]}
[0m10:15:56.794094 [debug] [MainThread]: Flushing usage events
[0m10:15:57.213167 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:12:24.111035 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067823c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109ae3c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109ae3b10>]}


============================== 14:12:24.113770 | c90ad7e3-5307-4f64-ae1f-bc39a8982fd5 ==============================
[0m14:12:24.113770 [info ] [MainThread]: Running with dbt=1.9.0
[0m14:12:24.114084 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/diaw/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt parse', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:12:24.114347 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/diaw/Downloads/dbt_notlimitail_tl/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:12:24.116054 [debug] [MainThread]: Resource report: {"command_name": "parse", "command_success": false, "command_wall_clock_time": 0.04169221, "process_in_blocks": "0", "process_kernel_time": 0.125418, "process_mem_max_rss": "100384768", "process_out_blocks": "0", "process_user_time": 0.575561}
[0m14:12:24.116316 [debug] [MainThread]: Command `dbt parse` failed at 14:12:24.116268 after 0.04 seconds
[0m14:12:24.116482 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a0b360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1099cf650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10996b680>]}
[0m14:12:24.116640 [debug] [MainThread]: Flushing usage events
[0m14:12:24.554851 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:40:38.246147 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110e67550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110eaf1d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110eca290>]}


============================== 16:40:38.250954 | a42bcda9-ce9e-407f-8c28-39f523239c22 ==============================
[0m16:40:38.250954 [info ] [MainThread]: Running with dbt=1.9.10
[0m16:40:38.251270 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'log_format': 'default', 'introspect': 'True', 'use_experimental_parser': 'False', 'fail_fast': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'debug': 'False', 'no_print': 'None', 'empty': 'None', 'target_path': 'None', 'warn_error': 'None', 'log_path': 'logs', 'log_cache_events': 'False', 'write_json': 'True', 'quiet': 'False', 'indirect_selection': 'eager', 'send_anonymous_usage_stats': 'True', 'cache_selected_only': 'False', 'use_colors': 'True', 'version_check': 'True', 'printer_width': '80', 'profiles_dir': '/Users/diaw/.dbt', 'invocation_command': 'dbt parse', 'static_parser': 'True'}
[0m16:40:38.251563 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/diaw/Downloads/dbt_notlimitail_tl/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:40:38.377984 [debug] [MainThread]: Resource report: {"command_name": "parse", "command_success": false, "command_wall_clock_time": 0.17394063, "process_in_blocks": "0", "process_kernel_time": 0.1611, "process_mem_max_rss": "106348544", "process_out_blocks": "0", "process_user_time": 0.786687}
[0m16:40:38.378673 [debug] [MainThread]: Command `dbt parse` failed at 16:40:38.378543 after 0.17 seconds
[0m16:40:38.379151 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1043f4fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110ee6e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104451b10>]}
[0m16:40:38.379536 [debug] [MainThread]: Flushing usage events
[0m16:40:38.786655 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:52:00.676796 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1042de3c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067efb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067efd90>]}


============================== 10:52:00.679672 | f4c244cb-ba3c-404d-8621-c58cd9016f2d ==============================
[0m10:52:00.679672 [info ] [MainThread]: Running with dbt=1.9.0
[0m10:52:00.679984 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/diaw/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:52:00.680365 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/diaw/Downloads/dbt_notlimitail_tl/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:52:00.725985 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.0856535, "process_in_blocks": "0", "process_kernel_time": 0.12761, "process_mem_max_rss": "100466688", "process_out_blocks": "0", "process_user_time": 0.571313}
[0m10:52:00.726361 [debug] [MainThread]: Command `dbt run` failed at 10:52:00.726303 after 0.09 seconds
[0m10:52:00.726565 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106713230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1066eb530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106663790>]}
[0m10:52:00.726743 [debug] [MainThread]: Flushing usage events
[0m10:52:01.162049 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:08:26.613123 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105d7a7b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cc39d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cc3890>]}


============================== 14:08:26.616044 | 5e12fab8-243c-4cd7-ba2f-f0d644636302 ==============================
[0m14:08:26.616044 [info ] [MainThread]: Running with dbt=1.9.0
[0m14:08:26.616350 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/diaw/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:08:26.616614 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/diaw/Downloads/dbt_notlimitail_tl/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:08:26.618198 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.039179042, "process_in_blocks": "0", "process_kernel_time": 0.094597, "process_mem_max_rss": "102973440", "process_out_blocks": "0", "process_user_time": 0.56481}
[0m14:08:26.618427 [debug] [MainThread]: Command `dbt run` failed at 14:08:26.618380 after 0.04 seconds
[0m14:08:26.618582 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106bbb100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106b2fbf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106b8a250>]}
[0m14:08:26.618723 [debug] [MainThread]: Flushing usage events
[0m14:08:27.013359 [debug] [MainThread]: An error was encountered while trying to flush usage events
